# Generated by Django 2.2.5 on 2019-10-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('places', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Places')),
            ],
        ),
        migrations.CreateModel(
            name='enAddress',
            fields=[
                ('descriptions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Descriptions')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hkAddress',
            fields=[
                ('descriptions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Descriptions')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
