# Generated by Django 2.2.5 on 2019-10-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191014_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='lon',
            new_name='lng',
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='places',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='descriptions', serialize=False, to='api.Places'),
        ),
        migrations.AlterField(
            model_name='enaddress',
            name='descriptions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enAddress', serialize=False, to='api.Descriptions'),
        ),
        migrations.AlterField(
            model_name='hkaddress',
            name='descriptions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hkAddress', serialize=False, to='api.Descriptions'),
        ),
    ]
