# Generated by Django 2.2.5 on 2019-10-17 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191016_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('descriptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.Places')),
            ],
        ),
    ]
