# Generated by Django 2.2.5 on 2019-10-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptions',
            new_name='places',
        ),
    ]
